### PR TITLE
Use GitHub Container Registry in GitHub Action

### PR DESCRIPTION
**Pull request by splitt3r**
Should be a bit faster and no rate limiting.

### CODE REVIEW

**Review by drupol — COMMENTED** [review]
:+1:

**Comment by splitt3r** [comment]
Ping @koppor any opinion about this?

**Comment by rugk** [comment]
Yeah, faster sounds good, given this is really, slow, see #7.

**Comment by rugk** [comment]
Any news @UweZiegenhagen @koppor? Can this just be merged?

It would make builds much faster and the current long build time the CI spends with downloading/building files is very annoying…

**Comment by rugk** [comment]
:tada: Thanks a lot! I hope we get a huge speedup now. :smiley:

**Comment by splitt3r** [comment]
For me it went down to 3 minutes from 6 minutes which is pretty nice 😃

**Pull request merged**
